services:

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    # so you don’t accidentally tear down CI when you deploy your app:
    profiles: 
      - ci

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - jenkins       # ensures Jenkins is up first
    profiles:
      - app

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://backend:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    profiles:
      - app

volumes:
  jenkins_home:

