services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://192.168.1.13:3001
    ports:
      - "3000:80"
    depends_on:
      - backend

